import './globals.css'
import { Inter } from 'next/font/google'
import { Header, Footer } from "../components";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'BYHS Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
