import { allProspectiveStudentsPosts } from 'contentlayer/generated';
import Link from "next/link";

import { StyledContents } from './style';

export const metadata = {
  title: '예비 입학생',
  description: 'Generated by create next app',
}

const students = () => (
  <div>
    <StyledContents>
      <div className="contents-container">
        <h1 className="page-title">예비 입학생</h1>
        <h1 className="page-content">예비 입학생 페이지입니다.</h1>
        {allProspectiveStudentsPosts.map((post) => (
          <article key={post._id}>
            <Link href={post._raw.flattenedPath}>
              <p className="post-date">{post.date}</p>
              <h1 className="post-title">{post.title}</h1>
              <p className="post-author">{post.author}</p>
            </Link>
          </article>
        ))}
      </div>
    </StyledContents>
  </div>
)

export default students;